'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SinglePlayerApartment.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //Property Owner
        '''3ASowner &quot;None&quot;
        '''4IWowner &quot;None&quot;
        '''DPHwoner &quot;None&quot;
        '''DPHHLowner &quot;None&quot;
        '''ETowner &quot;None&quot;
        '''4IWHLowner &quot;None&quot;
        '''ETHLowner &quot;None&quot;
        '''RMHLowner &quot;None&quot;
        '''TTHLowner &quot;None&quot;
        '''RMowner &quot;None&quot;
        '''SSowner &quot;None&quot;
        '''TTowner &quot;None&quot;
        '''WPowner &quot;None&quot;
        '''VPBowner &quot;None&quot;
        '''2044NCowner &quot;None&quot;
        '''2862HAowner &quot;None&quot;
        '''2868HAowner &quot;None&quot;
        '''3655WODowner &quot;None&quot;
        '''2045NCowner &quot;None&quot;
        '''2117MRowner &quot;None&quot;
        '''2874HAowner &quot;None&quot;
        '''3677WMDowner &quot;None&quot;
        '''2113MWTowner &quot;None&quot;
        '''ETP1owner &quot;None&quot;
        '''ETP2owner &quot;None&quot;
        '''ETP3owner &quot;None&quot;
        '''CAowner &quot;None&quot;
        '''B [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MySave() As String
            Get
                Return ResourceManager.GetString("MySave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleName &quot;&quot;
        '''VehicleModel &quot;&quot;
        '''PrimaryColor &quot;&quot;
        '''SecondaryColor &quot;&quot;
        '''PearlescentColor &quot;&quot;
        '''HasCustomPrimaryColor &quot;&quot;
        '''HasCustomSecondaryColor &quot;&quot;
        '''CustomPrimaryColorRed &quot;&quot;
        '''CustomPrimaryColorGreen &quot;&quot;
        '''CustomPrimaryColorBlue &quot;&quot;
        '''CustomSecondaryColorRed &quot;&quot;
        '''CustomSecondaryColorGreen &quot;&quot;
        '''CustomSecondaryColorBlue &quot;&quot;
        '''RimColor &quot;&quot;
        '''HasNeonLightBack &quot;&quot;
        '''HasNeonLightFront &quot;&quot;
        '''HasNeonLightLeft &quot;&quot;
        '''HasNeonLightRight &quot;&quot;
        '''NeonColorRed &quot;&quot;
        '''NeonColorGreen &quot;&quot;
        '''NeonColorBlue &quot;&quot;
        '''TyreSmokeColorRed &quot;&quot;
        '''TyreSmokeColorGreen &quot;&quot;
        '''T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vehicle() As String
            Get
                Return ResourceManager.GetString("vehicle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
