'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MlastPosX() As Single
            Get
                Return CType(Me("MlastPosX"),Single)
            End Get
            Set
                Me("MlastPosX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MlastPosY() As Single
            Get
                Return CType(Me("MlastPosY"),Single)
            End Get
            Set
                Me("MlastPosY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MlastPosZ() As Single
            Get
                Return CType(Me("MlastPosZ"),Single)
            End Get
            Set
                Me("MlastPosZ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FlastPosX() As Single
            Get
                Return CType(Me("FlastPosX"),Single)
            End Get
            Set
                Me("FlastPosX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FlastPosY() As Single
            Get
                Return CType(Me("FlastPosY"),Single)
            End Get
            Set
                Me("FlastPosY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FlastPosZ() As Single
            Get
                Return CType(Me("FlastPosZ"),Single)
            End Get
            Set
                Me("FlastPosZ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TlastPosX() As Single
            Get
                Return CType(Me("TlastPosX"),Single)
            End Get
            Set
                Me("TlastPosX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TlastPosY() As Single
            Get
                Return CType(Me("TlastPosY"),Single)
            End Get
            Set
                Me("TlastPosY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TlastPosZ() As Single
            Get
                Return CType(Me("TlastPosZ"),Single)
            End Get
            Set
                Me("TlastPosZ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("F6")>  _
        Public Property Mechanic() As Global.System.Windows.Forms.Keys
            Get
                Return CType(Me("Mechanic"),Global.System.Windows.Forms.Keys)
            End Get
            Set
                Me("Mechanic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlwaysEnableMPMaps() As Boolean
            Get
                Return CType(Me("AlwaysEnableMPMaps"),Boolean)
            End Get
            Set
                Me("AlwaysEnableMPMaps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HasLowriderUpdate() As Boolean
            Get
                Return CType(Me("HasLowriderUpdate"),Boolean)
            End Get
            Set
                Me("HasLowriderUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.671.1")>  _
        Public Property GameVersion() As String
            Get
                Return CType(Me("GameVersion"),String)
            End Get
            Set
                Me("GameVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NeverEnableMPMaps() As Boolean
            Get
                Return CType(Me("NeverEnableMPMaps"),Boolean)
            End Get
            Set
                Me("NeverEnableMPMaps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CreateFileMethod() As Integer
            Get
                Return CType(Me("CreateFileMethod"),Integer)
            End Get
            Set
                Me("CreateFileMethod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property ThreeAltaStreet() As String
            Get
                Return CType(Me("ThreeAltaStreet"),String)
            End Get
            Set
                Me("ThreeAltaStreet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property FourIntegrityWay() As String
            Get
                Return CType(Me("FourIntegrityWay"),String)
            End Get
            Set
                Me("FourIntegrityWay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property DelPerroHeight() As String
            Get
                Return CType(Me("DelPerroHeight"),String)
            End Get
            Set
                Me("DelPerroHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property DreamTower() As String
            Get
                Return CType(Me("DreamTower"),String)
            End Get
            Set
                Me("DreamTower") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property EclipseTower() As String
            Get
                Return CType(Me("EclipseTower"),String)
            End Get
            Set
                Me("EclipseTower") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property RichardMajestic() As String
            Get
                Return CType(Me("RichardMajestic"),String)
            End Get
            Set
                Me("RichardMajestic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property TinselTower() As String
            Get
                Return CType(Me("TinselTower"),String)
            End Get
            Set
                Me("TinselTower") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property VespucciBlvd() As String
            Get
                Return CType(Me("VespucciBlvd"),String)
            End Get
            Set
                Me("VespucciBlvd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property WeazelPlaza() As String
            Get
                Return CType(Me("WeazelPlaza"),String)
            End Get
            Set
                Me("WeazelPlaza") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property Hillcrest2862() As String
            Get
                Return CType(Me("Hillcrest2862"),String)
            End Get
            Set
                Me("Hillcrest2862") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property Hillcrest2868() As String
            Get
                Return CType(Me("Hillcrest2868"),String)
            End Get
            Set
                Me("Hillcrest2868") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property Hillcrest2874() As String
            Get
                Return CType(Me("Hillcrest2874"),String)
            End Get
            Set
                Me("Hillcrest2874") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property MadWayne2113() As String
            Get
                Return CType(Me("MadWayne2113"),String)
            End Get
            Set
                Me("MadWayne2113") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property MiltonRd2117() As String
            Get
                Return CType(Me("MiltonRd2117"),String)
            End Get
            Set
                Me("MiltonRd2117") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property NorthConker2044() As String
            Get
                Return CType(Me("NorthConker2044"),String)
            End Get
            Set
                Me("NorthConker2044") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property NorthConker2045() As String
            Get
                Return CType(Me("NorthConker2045"),String)
            End Get
            Set
                Me("NorthConker2045") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property Whispymound3677() As String
            Get
                Return CType(Me("Whispymound3677"),String)
            End Get
            Set
                Me("Whispymound3677") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property WildOats3655() As String
            Get
                Return CType(Me("WildOats3655"),String)
            End Get
            Set
                Me("WildOats3655") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property CougarAve() As String
            Get
                Return CType(Me("CougarAve"),String)
            End Get
            Set
                Me("CougarAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property BayCityAve() As String
            Get
                Return CType(Me("BayCityAve"),String)
            End Get
            Set
                Me("BayCityAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property MiltonRd0184() As String
            Get
                Return CType(Me("MiltonRd0184"),String)
            End Get
            Set
                Me("MiltonRd0184") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SouthRockfordDr0325() As String
            Get
                Return CType(Me("SouthRockfordDr0325"),String)
            End Get
            Set
                Me("SouthRockfordDr0325") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SouthMoMiltonDr() As String
            Get
                Return CType(Me("SouthMoMiltonDr"),String)
            End Get
            Set
                Me("SouthMoMiltonDr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property LasLagunasBlvd0604() As String
            Get
                Return CType(Me("LasLagunasBlvd0604"),String)
            End Get
            Set
                Me("LasLagunasBlvd0604") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SpanishAve() As String
            Get
                Return CType(Me("SpanishAve"),String)
            End Get
            Set
                Me("SpanishAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property BlvdDelPerro() As String
            Get
                Return CType(Me("BlvdDelPerro"),String)
            End Get
            Set
                Me("BlvdDelPerro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property PowerSt() As String
            Get
                Return CType(Me("PowerSt"),String)
            End Get
            Set
                Me("PowerSt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property ProsperitySt() As String
            Get
                Return CType(Me("ProsperitySt"),String)
            End Get
            Set
                Me("ProsperitySt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SanVitasSt() As String
            Get
                Return CType(Me("SanVitasSt"),String)
            End Get
            Set
                Me("SanVitasSt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property LasLagunasBlvd2143() As String
            Get
                Return CType(Me("LasLagunasBlvd2143"),String)
            End Get
            Set
                Me("LasLagunasBlvd2143") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property TheRoyale() As String
            Get
                Return CType(Me("TheRoyale"),String)
            End Get
            Set
                Me("TheRoyale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property HangmanAve() As String
            Get
                Return CType(Me("HangmanAve"),String)
            End Get
            Set
                Me("HangmanAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SustanciaRd() As String
            Get
                Return CType(Me("SustanciaRd"),String)
            End Get
            Set
                Me("SustanciaRd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property ProcopioDr4401() As String
            Get
                Return CType(Me("ProcopioDr4401"),String)
            End Get
            Set
                Me("ProcopioDr4401") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property ProcopioDr4584() As String
            Get
                Return CType(Me("ProcopioDr4584"),String)
            End Get
            Set
                Me("ProcopioDr4584") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property SouthRockfordDr0112() As String
            Get
                Return CType(Me("SouthRockfordDr0112"),String)
            End Get
            Set
                Me("SouthRockfordDr0112") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property ZancudoAve() As String
            Get
                Return CType(Me("ZancudoAve"),String)
            End Get
            Set
                Me("ZancudoAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property PaletoBlvd() As String
            Get
                Return CType(Me("PaletoBlvd"),String)
            End Get
            Set
                Me("PaletoBlvd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property GrapeseedAve() As String
            Get
                Return CType(Me("GrapeseedAve"),String)
            End Get
            Set
                Me("GrapeseedAve") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property PreviewPointX() As Integer
            Get
                Return CType(Me("PreviewPointX"),Integer)
            End Get
            Set
                Me("PreviewPointX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property PreviewPointY() As Integer
            Get
                Return CType(Me("PreviewPointY"),Integer)
            End Get
            Set
                Me("PreviewPointY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property VehicleSpawn() As Integer
            Get
                Return CType(Me("VehicleSpawn"),Integer)
            End Get
            Set
                Me("VehicleSpawn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Volume() As Integer
            Get
                Return CType(Me("Volume"),Integer)
            End Get
            Set
                Me("Volume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("235")>  _
        Public Property MechanicPad() As Integer
            Get
                Return CType(Me("MechanicPad"),Integer)
            End Get
            Set
                Me("MechanicPad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("223")>  _
        Public Property SecondMechanicPad() As Integer
            Get
                Return CType(Me("SecondMechanicPad"),Integer)
            End Get
            Set
                Me("SecondMechanicPad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RADIO_01_CLASS_ROCK")>  _
        Public Property RadioStation() As String
            Get
                Return CType(Me("RadioStation"),String)
            End Get
            Set
                Me("RadioStation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RefreshGrgVehs() As Boolean
            Get
                Return CType(Me("RefreshGrgVehs"),Boolean)
            End Get
            Set
                Me("RefreshGrgVehs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enable")>  _
        Public Property MazeBankWest() As String
            Get
                Return CType(Me("MazeBankWest"),String)
            End Get
            Set
                Me("MazeBankWest") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SinglePlayerApartment.My.MySettings
            Get
                Return Global.SinglePlayerApartment.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
